# Generated by Django 4.1.5 on 2023-03-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="admin",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_editor",
            new_name="editor",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_student",
            new_name="student",
        ),
        migrations.AddField(
            model_name="user",
            name="staff",
            field=models.BooleanField(default=True, verbose_name="Staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
