# Generated by Django 4.1.5 on 2023-03-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_is_admin_user_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
